name: 'PaperFrame'
version: 0.0.5
author: 'cth451'
description: 'Commands to manipulate item frames'
main: me.cth451.paperframe.PaperFramePlugin
api-version: 1.18
commands:
  frameprotect:
    description: |
      Protect / un-protect / Check the item frame you are looking at
      (no arguments) = check protection status
      --on, -1 = turn on protection
      --off, -0 = turn off protection
    usage: "/frameprotect [--on|--off]"
    permission: "paperframe.protect"
    aliases:
      - fprotect
      - fprot
  framehighlight:
    description: |
      Toggle highlight status of item frames near you
      -h = hidden ones only
      -p = protected ones only
      -r N = highlight within radius N
    usage: "/framehighlight [-h] [-p] [-r radius]"
    permission: "paperframe.highlight"
    aliases:
      - fh
  frameshowhide:
    description: "Toggle invisible status of the frame you are looking at"
    usage: "/frameshowhide"
    permission: "paperframe.showhide"
    aliases:
      - fsh
  frameconfigreload:
    description: "Reload PaperFrame plugin config.yml"
    usage: "/frameconfigreload"
    permission: "paperframe.configreload"
    aliases:
      - fcr
  framestat:
    description: "Check item frame status"
    usage: "/framestat"
    permission: "paperframe.stat"
    aliases:
      - fstat
  framemaps:
    description: |
      Spawn protected hidden item frames containing specific maps at your cursor.
      -g = spawn with glowing item frames
      -a = append only, otherwise existing frames in the occupying space will be removed
    usage: "/framemaps [-g] [-a] id1 id2 ...."
    permission: "paperframe.mapstack"
    aliases:
      - fmaps
permissions:
  paperframe.*:
    description: "Gives access to all PaperFrame commands"
    default: false
    children:
      paperframe.protect: true
      paperframe.highlight: true
      paperframe.showhide: true
      paperframe.configreload: true
      paperframe.stat: true
      paperframe.mapstack: true
  paperframe.protect:
    description: "Allow use of /frameprotect"
    default: op
  paperframe.highlight:
    description: "Allow use of /framehighlight and /fh"
    default: true
  paperframe.showhide:
    description: "Allow use of /frameshowhide and /fsh"
    default: op
  paperframe.configreload:
    description: "Allow use of /frameconfigreload and /fcr"
    default: op
  paperframe.stat:
    description: "Allow use of /framestat and /fstat"
    default: true
  paperframe.mapstack:
    description: "Allow use of /framemaps and /fmaps"
    default: op