name: 'PaperFrame'
version: 0.0.9
author: 'cth451'
description: 'Commands to manipulate item frames'
main: me.cth451.paperframe.PaperFramePlugin
api-version: 1.18
softdepend:
  - WorldEdit
commands:
  frameprotect:
    description: Protect / un-protect the item frame you are looking at.
    usage: |
      /frameprotect [--on|--off] [-w]
      --on, -1 = turn on protection
      --off, -0 = turn off protection
      Neither = toggle
      -w = operate within WorldEdit selected cuboid instead of the frame under cursor
    permission: "paperframe.protect"
    aliases:
      - fprotect
      - fprot
  framehighlight:
    description: Toggle highlight status of item frames near you. Multiple filters maybe stacked together.
    usage: |
      /framehighlight [-hpse] [-r radius | -w]
      -h = hidden ones only
      -p = protected ones only
      -s = overlapping / stacked ones only
      -e = empty frames only
      -r N = highlight within radius N
      -w = highlight within WorldEdit selected cuboid, overrides -r
    permission: "paperframe.highlight"
    aliases:
      - fh
  frameshowhide:
    description: |
      Toggle invisible status of the frame you are looking at
    usage: |
      /frameshowhide [--on|--off] [-w]
      --on, -1 = make invisible
      --off, -0 = make visible
      Neither = toggle
      -w = operate within WorldEdit selected cuboid instead of the frame under cursor
    permission: "paperframe.showhide"
    aliases:
      - fsh
  frameconfigreload:
    description: "Reload PaperFrame plugin config.yml"
    usage: "/frameconfigreload"
    permission: "paperframe.configreload"
    aliases:
      - fcr
  framestat:
    description: "Check item frame status"
    usage: "/framestat"
    permission: "paperframe.stat"
    aliases:
      - fstat
  framemaps:
    description: |
      Spawn protected hidden item frames containing specific maps on the block face under cross hair.
    usage: |
      /framemaps [-ghpa] id1 id2 ....
      -g = new frames should be glowing
      -h = new frames should be hidden
      -p = new frames should be protected
      -a = append only, otherwise existing frames in the occupying space will be removed
    permission: "paperframe.mapstack"
    aliases:
      - fmaps
  frameunmap:
    description: |
      Destroy all item frames on the block face under your cursor
    usage: |
      /frameunmap [-w]
      -w = operate within WorldEdit selected cuboid instead of the frame under cursor
    permission: "paperframe.mapstack"
    aliases:
      - funmap
  frame2d:
    description: |
      Place tiles one by one onto a flat rectangle of frames with top-left corner under cursor. All frames must already exist.
      Existing items in the frames will be deleted and replaced. All map ids will be validated prior to execution.
    usage: |
      /frame2d {-n name | -w W -h H ids ...}
        -n retrieve tile set information from a tile set metadata server.
      Alternatively use the following parameters:
        -w W, -h N specify width and height respectively.
      
      Map IDs can be specified in the following ways:
      - "X" This exact map with ID exactly equal to X;
      - "X:Y" Maps between X and Y inclusive in that order;
      - "X+N" X and upwards to X+N (inclusive);
      - "X+-N" X+N and downwards to X (inclusive).
    permission: "paperframe.frametiling"
    aliases:
      - f2d
permissions:
  paperframe.*:
    description: "Gives access to all PaperFrame commands"
    default: false
    children:
      paperframe.protect: true
      paperframe.highlight: true
      paperframe.showhide: true
      paperframe.configreload: true
      paperframe.stat: true
      paperframe.mapstack: true
  paperframe.protect:
    description: "Allow use of /frameprotect"
    default: op
  paperframe.highlight:
    description: "Allow use of /framehighlight and /fh"
    default: true
  paperframe.showhide:
    description: "Allow use of /frameshowhide and /fsh"
    default: op
  paperframe.configreload:
    description: "Allow use of /frameconfigreload and /fcr"
    default: op
  paperframe.stat:
    description: "Allow use of /framestat and /fstat"
    default: true
  paperframe.mapstack:
    description: "Allow use of /framemaps, /fmaps, /frameunmap, /funmap and /f2d"
    default: op
