name: 'PaperFrame'
version: 0.0.9
author: 'cth451'
description: 'Commands to manipulate item frames'
main: me.cth451.paperframe.PaperFramePlugin
api-version: 1.18
softdepend:
  - WorldEdit
commands:
  frameprotect:
    description: |
      Protect / un-protect the item frame you are looking at
      --on, -1 = turn on protection
      --off, -0 = turn off protection
      Neither = toggle
      
      -w = operate within WorldEdit selected cuboid instead of the frame under cursor
    usage: "/frameprotect <--on|--off> <-w>"
    permission: "paperframe.protect"
    aliases:
      - fprotect
      - fprot
  framehighlight:
    description: |
      Toggle highlight status of item frames near you. Multiple filters maybe stacked together.
      -h = hidden ones only
      -p = protected ones only
      -s = overlapping / stacked ones only
      -e = empty frames only
      -r N = highlight within radius N
      -w = highlight within WorldEdit selected cuboid, overrides -r
    usage: "/framehighlight <-hpse> [-r radius|-w]"
    permission: "paperframe.highlight"
    aliases:
      - fh
  frameshowhide:
    description: |
      Toggle invisible status of the frame you are looking at
      --on, -1 = make invisible
      --off, -0 = make visible
      Neither = toggle

      -w = operate within WorldEdit selected cuboid instead of the frame under cursor
    usage: "/frameshowhide <--on|--off> <-w>"
    permission: "paperframe.showhide"
    aliases:
      - fsh
  frameconfigreload:
    description: "Reload PaperFrame plugin config.yml"
    usage: "/frameconfigreload"
    permission: "paperframe.configreload"
    aliases:
      - fcr
  framestat:
    description: "Check item frame status"
    usage: "/framestat"
    permission: "paperframe.stat"
    aliases:
      - fstat
  framemaps:
    description: |
      Spawn protected hidden item frames containing specific maps on the block face under cross hair.
      -g = spawn with glowing item frames
      -a = append only, otherwise existing frames in the occupying space will be removed
    usage: "/framemaps <-ga> id1 id2 ...."
    permission: "paperframe.mapstack"
    aliases:
      - fmaps
  frameunmap:
    description: |
      Destroy all item frames on the block face under your cursor
      -w = operate within WorldEdit selected cuboid instead of the frame under cursor
    usage: "/frameunmap <-w>"
    permission: "paperframe.mapstack"
    aliases:
      - funmap
permissions:
  paperframe.*:
    description: "Gives access to all PaperFrame commands"
    default: false
    children:
      paperframe.protect: true
      paperframe.highlight: true
      paperframe.showhide: true
      paperframe.configreload: true
      paperframe.stat: true
      paperframe.mapstack: true
  paperframe.protect:
    description: "Allow use of /frameprotect"
    default: op
  paperframe.highlight:
    description: "Allow use of /framehighlight and /fh"
    default: true
  paperframe.showhide:
    description: "Allow use of /frameshowhide and /fsh"
    default: op
  paperframe.configreload:
    description: "Allow use of /frameconfigreload and /fcr"
    default: op
  paperframe.stat:
    description: "Allow use of /framestat and /fstat"
    default: true
  paperframe.mapstack:
    description: "Allow use of /framemaps, /fmaps, /frameunmap and /funmap"
    default: op
