name: 'PaperFrame'
version: 0.0.3
author: 'cth451'
description: 'Commands to manipulate item frames'
main: me.cth451.paperframe.PaperFramePlugin
api-version: 1.18
commands:
  frameprotect:
    description: |
      Protect / un-protect the item frame you are looking at
      --on, -1 = turn on protection
      --off, -0 = turn off protection
    usage: "/frameprotect --on|--off"
    permission: "paperframe.protect"
    aliases:
      - fprotect
  framehighlight:
    description: |
      Toggle highlight status of item frames near you
      -h = hidden ones only
      -p = protected ones only
      -r N = highlight within radius N
    usage: "/framehighlight [-h] [-p] [-r radius]"
    permission: "paperframe.highlight"
    aliases:
      - fh
  frameshowhide:
    description: "Toggle invisible status of the frame you are looking at"
    usage: "/frameshowhide"
    permission: "paperframe.showhide"
    aliases:
      - fsh
  frameconfigreload:
    description: "Reload PaperFrame plugin config.yml"
    usage: "/frameconfigreload"
    permission: "paperframe.configreload"
    aliases:
      - fcr
permissions:
  paperframe.*:
    description: "Gives access to all PaperFrame commands"
    children:
      paperframe.protect: true
      paperframe.highlight: true
      paperframe.showhide: true
      paperframe.configreload: true
  paperframe.protect:
    description: "Allow use of /frameprotect"
    default: op
  paperframe.highlight:
    description: "Allow use of /framehighlight and /fh"
    default: true
  paperframe.showhide:
    description: "Allow use of /frameshowhide and /fsh"
    default: op
  paperframe.configreload:
    description: "Allow use of /frame/configreload and /fcr"
    default: op